### ISSUE TITLE
To Class, or Not To Class?

### ISSUE THREAD

**Issue by waynew** [CraigHissett/PiVidPlayer#1]
Looking a the code that you have so far just reminded me how much I love Python because you can program with or without classes and there's really not that much difference.

Plus, not sure if you're aware of this or not, but in Python _everything_ is an object (i.e. an instance of a class):

```
>>> (3).__str__()
'3'
```

Even plain ol' numbers. Though, you don't actually have to care about it most of the time. So you just have to make a decision about what works best in _your_ mind. You can either organize your application out in one module/file, several smaller modules, or classes, or some combination. Based on your README, here's are a couple of options
# One file, all the things:

```
def show_settings():
    '''
    Show the settings menu. When the ``Save`` or ``Cancel`` button is pressed, return.
    '''
    # Code would actually go here, of course

def show_video(filename):
    '''
    Play video with the provided ``filename``. If pause button is pressed,
    pause the video. If stop button is pressed, stop the video and return.
    '''

def show_loading():
    '''
    Show loading dialog and search for playlists
    '''

def show_playlists():
    '''
    Show playlist menu. Return the playlist that was selected, or ``None`` if
    the cancel button was pressed.
    '''
```

Naturally the file will be much, _much_ larger than that, because you'll have to keep all the supporting functions and data around, along with writing the logic :smile: 
# One File, all the classes

Similar to above, but you might have something like this:

```
class Screen:
     def loop(self):
        '''
        Show this screen and handle button presses and other events.
        '''
        # get events and respond to them

    def respond(self, event):
        raise NotImplementedError('respond not yet implemented')

class Settings(Screen):
    def respond(self, event):
        '''
        Handle events. Event type may be one of the following:

        * ``save_btn_pressed``
        * ``cancel_btn_pressed``
        * other events TBD
        '''

# Other screens would go here
```

Another alternative would be to do one of the above, but separate the classes/functions out into related modules, e.g.

```
├── player.py
├── settings.py
└── splash.py
```

But you're writing the program, so whatever makes the most sense to **you** is what you should choose. Good luck! :+1:

**Comment by CraigHissett** [comment]
Thank you so much for the breakdown, Wayne - it's exactly the help I was looking for!
I had previously been advised to write one big script and then break it down afterwards but once the script gets bigger I fear i'd simply get lost in it!
Also, given the nature I tend to work in (little bits, here and there), I feel breaking it down will make it much more manageable for me. If I break it up into separate scripts I can focus on that particular area of the code without having the distraction of the rest.
I think tonight I am going to try and write my GUI stuff into a Class. At present I only have two screens to show (currently written in my PiVidPlayer.py file), but hoping to add a lot more. Once I have a nicely structured Screen class it'll be easy to set others up, 
I hope :-)

**Comment by CraigHissett** [comment]
Hi Wayne!
I've just typed up a hypothetical main.py, taking into consideration the top-down approach.
Going to hopefully recreate my defs in the associated python scripts to hopefully gain me some functionality!
Does it make sense?!

**Comment by waynew** [comment]
:+1: Looks reasonable to me :)

**Comment by CraigHissett** [comment]
Cheers buddy! Now... to make it work!!!
I should be ok with most of it, just a bit stumped with using pyOMXPlayer at the mo.

**Comment by CraigHissett** [comment]
Heyup matey!
Just a quick update, and a thank you for your advice. Your top down suggestion has really helped me get the main body of this code up and running!
Just going through and getting the code working as it should on my Pi, making small amendments as i go, and ensuring the lot is backed up on here :-)
Still struggling to fathom how the pyOMXPlayer will be integrated, but I'm getting there! :-)

**Comment by waynew** [comment]
:+1: Nice! Looks pretty good so far :)

If you're interested in making your code more idiomatic I can offer some suggestions, but otherwise it looks like it's shaping up nicely :)

It looks like the pyOMXPlayer api is pretty simplistic - it's either stopped, paused, or playing. You can seek, if you want, but it doesn't look to do any more than that.

```
from pyomxplayer import OMXPlayer
player = OMXPlayer('/path/to/your/video.mp4')

player.toggle_pause()

player.stop()
```

The only other feature it's got is toggling the subtitles, if your video has them.

What you might consider doing is creating a player class that looks something like this:

```
class Player:
    def __init__(self, playlist_file, autoplay=True):
        with open(playlist_file) as f:
            self.playlist = [line.strip() for line in f]
        self.cur_pos = 0
        self._omx = None

    @property
     def current_file(self):
         return self.playlist[self.cur_pos]

     def play(self):
         if self._omx is None:
             self._omx = OMXPlayer(self.current_file)
         elif self._omx.paused:
             self._omx.toggle_pause()

    def stop(self):
        if self._omx is not None:
            self._omx.stop()
            self._omx = None

    def next(self):
        self.stop()
        # We don't want to seek past the end of the playlist.
        # Alternatively, you could add an 'else' clause that resets
        # self.cur_pos = 0 to wrap the playlist around
        if self.cur_pos < len(self.playlist)-1:
            self.cur_pos += 1
            self.play()

    def prev(self):
         # Don't go back before the beginning of the playlist
         # You could also implement something like in `next()` and loop
         # to the end of the playlist. That would be self.cur_pos = len(self.playlist)-1
         self.cur_pos = max(0, self.cur_pos - 1)
```

I'm not entirely sure about automatically advancing your playlist to the next video, though. You might have to do something tricky - it doesn't look like [pyOMXplayer](https://github.com/jbaiter/pyomxplayer/blob/master/pyomxplayer.py) has anything handy. You might hack something together using the position... but what would be super nice is if there was a way to do something like `self._omx = OMXPlayer(self.current_file, on_stop=self.next)`

Anyway, HTH, and good luck!

**Comment by CraigHissett** [comment]
Ah, thank you so much mate - you have no idea how much that has helped.
The pyOMXplayer example confused me; there's a lot of extra information included in it and I was unsure as to what was necessary to make a video play.
Excuse my ignorance, but how does the class fit in in this instance?
I see that the class is providing the functions for play, pause, previous and next (which are the core functions I need), but I am unsure how to take advantage of them.

Would it be something like:

<addr>PiPlayer = Player(MyVideoToBePlayed)
PiPlayer.play
</addr>

?

At current my method of playing lives in playlists.py, and would theoretically play a file by providing a playlist file name and a line number. It then searches the playlist text file (containing the file locations of all videos to be played) for the specified line, then provides the path on that line to be played:

<addr>def play(SelectedPlaylist, PlayNo):
    #Set up the OMX player code here
    PL = open(SelectedPlaylist, "rw+")
    video = PL.readline(PlayNo)
    omx = OMXPlayer(video)
    omx.toggle_pause()
    #play 30 second snippet for demonstration purposes
    time.sleep(30)
    omx.stop()
</addr>

I would flipping love to integrate your class idea into my code. The penny is so close to dropping on this one it's flipping killing me!!

**Comment by waynew** [comment]
You could define that class within your **GUI.py** - or have a **player.py**, rather than **playlists.py**

So you'd have something like this:

```
import buttons, player

#or instead of player,

class Player:
     # rest of the code goes here

player = None

def check_for_keypress():
    global player
# other code you already have
    elif buttons.pressed==LB1
      #Select Playlist1, Load video 1
      player = Player("Peppa.txt")
    elif buttons.pressed==LB2
      #Select Playlist2
      player = Player("Barney.txt")
```

**Comment by CraigHissett** [comment]
You are a wonderful man! I had almost blinkered myself by thinking I must read playlists separately before passing to the player; i had overlooked your code doing it for me!
Tonight i will work on putting together player.py and removing the unnecessary tat from my playlists.py that is no longer needed. As for advancing to the next video... Now i have a chance of understanding the code i may have a look at other examples such as KenT2/pyomxplayer and the likes and see if they have conjured something up for skipping to the next video.
KenT2's example is something i had looked at when first starting out but it caused a migraine, ha ha.

Thanks again buddy, your help is greatly appreciated!

**Comment by waynew** [comment]
> thinking I must read playlists separately before passing to the player; i had overlooked your code doing it for me!

That's one of the things that it's useful to use classes (and sometimes modules) for.

It goes back to that top-down approach. Typically I'll ask myself something like, <i>Is there any reason that the **player** should **not** have the ability to read a playlist file?</i>

My answer was, "I can't think of any. It probably _should_ be able to take a playlist file."

That style of thinking is what drives the way I try to design most of the time - I keep breaking my problem in pieces and digging extra layers down until my problem is small enough. Like in this case, your problem is, "I want to let my kid play videos by pressing some buttons" (at the highest level). Keep breaking off pieces and it might look like this:
- I want to let them pick playlists
  - I will have playlists in the form of text files
    - I need to load these playlists into my video player
      - I can pass a filename to the player and it can open the file and read the lines to get the list of video files.

Then I just repeat that until my problem is solved :)
